# Generated by Django 4.0.6 on 2022-07-06 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('done', models.BooleanField(default=False)),
                ('creation_date', models.DateField(default=datetime.date)),
                ('deadline_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['deadline_date'],
            },
        ),
    ]
