# Generated by Django 4.0.6 on 2022-07-06 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateField(default=datetime.date(2022, 7, 6)),
        ),
    ]
